name: task-b manual

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./task_b
          file: ./task_b/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ inputs.tag }}

  test:
    runs-on: ubuntu-latest
    needs: docker
    services:
      web:
        image: ghcr.io/${{ github.repository }}:${{ inputs.tag }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 8080:80
    steps:
      - name: Test web server
        run: |
          curl http://127.0.0.1:8080/index.html
          echo "Successfully fetched index.html!"